#!/usr/bin/env bash
# Desplays information about the subdomains
function check_domain {
    domains=( "www" "lb-01" "web-01" "web-02" )
    for domain in "${domains[@]}";
    do
        dig "${domain}"."$1" | grep -A1 "ANSWER SECTION:" | \
        awk "FNR === 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}" var="${domain}"
    done
}

function check_subdomain {
    dig "${2}"."$1" | grep -A1 "ANSWER SECTION:" | \
    awk "FNR === 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}" var="${2}"
}

if [$# -lt 1]
then
    echo "Usage: $0 <domain> <subdomain>"
elif [$# -eq 1]
then
    check_domain "$1"
elif [$# -eq 2]
then
    check_subdomain "$1" "$2"
fi
