#!/usr/bin/env bash
# Desplays information about the subdomains
function check_dns_record {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        local subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            dispaly_dns_record "$domain" "$sub"
        done
    else
        dispaly_dns_record "$domain" "$subdomain"
    fi
}

function dispaly_dns_record {
    local domain=$1
    local subdomain=$2
    local fqdn="$subdomain.$domain"

    local record
    record=$(dig "$fqdn" +short A)

    if [ -n "$record" ]; then
        echo "The subdomain $subdomain is a A record and points to $record"
    else
        echo "No A record found for $fqdn"
    fi
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> <subdomain>"
    exit 1
fi

check_dns_record "$1" "$2"
