#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
script_name=$(basename "$0")
if [[ $# -lt 4 ]]; then
    echo "Usage: $script_name PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"; then
    echo "File transferred!"
else
    echo "File transfer failed!"
fi
