#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to the requirements asked in this task
apt-get update
apt-get install -y nginx

if [[ ! -f /etc/nginx/sites-available/default ]]; then
    cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;
}
EOF
fi

sed -i '/\}/i \
location /redirect_me { \
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
}' /etc/nginx/sites-available/redirect_me

ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

nginx -t

/usr/sbin/nginx -s reload
