#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to the requirements asked in this task
apt-get update
apt-get install -y nginx

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

nginx -t

/usr/sbin/nginx -s reload
