#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect custom HTTP header
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    add_header X-Served-By $HOSTNAME;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
