#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file
while IFS=: read -r user pass id gid uidi home command
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $command. $id's place is protected by the passcode $pass, more info about the user here: $uidi"
done < /etc/passwd
