#!/usr/bin/env bash
# Debugging script for Nginx
if ! id "nginx" &>/dev/null; then
    sudo useradd -r -s /bin/false nginx
fi

sudo sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx

sudo systemctl restart nginx
ps -aux | grep nginx
sudo netstat -tulnp | grep nginx
